/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BackupRecord {
  'version' : string,
  'timestamp' : bigint,
  'invoices' : Array<Invoice>,
  'medicines' : Array<Medicine>,
  'firmSettings' : [] | [FirmSettings],
  'doctors' : Array<Doctor>,
  'paymentRecords' : Array<[bigint, Array<PaymentRecord>]>,
}
export interface Doctor {
  'name' : string,
  'customPrices' : Array<[string, bigint]>,
  'shippingAddress' : string,
}
export interface FirmSettings {
  'contact' : string,
  'dilNumber' : string,
  'name' : string,
  'email' : string,
  'gstin' : string,
  'address' : string,
  'defaultShippingAddress' : string,
}
export interface Invoice {
  'gstAmount' : bigint,
  'amountPaid' : bigint,
  'grandTotal' : bigint,
  'totalProfit' : bigint,
  'invoiceNumber' : bigint,
  'timestamp' : bigint,
  'paymentType' : string,
  'amountDue' : bigint,
  'items' : Array<InvoiceItem>,
  'doctorName' : string,
  'subtotal' : bigint,
}
export interface InvoiceItem {
  'purchaseRate' : bigint,
  'expiryDate' : string,
  'sellingPrice' : bigint,
  'hsnCode' : string,
  'batchNumber' : string,
  'quantity' : bigint,
  'profit' : bigint,
  'amount' : bigint,
  'medicineName' : string,
}
export interface LedgerSummary {
  'totalCredit' : bigint,
  'totalPaid' : bigint,
  'outstandingBalance' : bigint,
  'doctorName' : string,
}
export interface Medicine {
  'mrp' : bigint,
  'purchaseRate' : bigint,
  'expiryDate' : string,
  'name' : string,
  'hsnCode' : string,
  'baseSellingRate' : bigint,
  'batchNumber' : string,
  'quantity' : bigint,
  'sampling' : bigint,
  'openingStock' : bigint,
}
export interface PaymentRecord {
  'invoiceNumber' : bigint,
  'timestamp' : bigint,
  'paymentDate' : string,
  'amount' : bigint,
}
export interface ProfitLossStats {
  'invoiceCount' : bigint,
  'totalCost' : bigint,
  'totalRevenue' : bigint,
  'profitMargin' : bigint,
  'netProfit' : bigint,
}
export type ProfitLossTimeFilter = { 'all' : null } |
  { 'monthly' : null } |
  { 'daily' : null } |
  { 'weekly' : null };
export interface _SERVICE {
  'addDoctor' : ActorMethod<[string, string], undefined>,
  'addOrUpdateMedicine' : ActorMethod<
    [string, bigint, bigint, string, string, string, bigint, bigint, bigint],
    undefined
  >,
  'backup' : ActorMethod<[], BackupRecord>,
  'createInvoice' : ActorMethod<
    [string, Array<[string, bigint]>, string],
    bigint
  >,
  'deleteDoctor' : ActorMethod<[string], undefined>,
  'deleteInvoice' : ActorMethod<[bigint], undefined>,
  'deleteMedicine' : ActorMethod<[string], undefined>,
  'getAllDoctorPrices' : ActorMethod<[string], Array<[string, bigint]>>,
  'getAllDoctors' : ActorMethod<[], Array<Doctor>>,
  'getAllInvoices' : ActorMethod<[], Array<Invoice>>,
  'getAllMedicines' : ActorMethod<[], Array<Medicine>>,
  'getAppPin' : ActorMethod<[], [] | [string]>,
  'getDoctor' : ActorMethod<[string], [] | [Doctor]>,
  'getDoctorLedgerSummary' : ActorMethod<[string], LedgerSummary>,
  'getDoctorMedicinePrice' : ActorMethod<[string, string], bigint>,
  'getFirmSettings' : ActorMethod<[], FirmSettings>,
  'getInvoice' : ActorMethod<[bigint], [] | [Invoice]>,
  'getInvoicePayments' : ActorMethod<[bigint], Array<PaymentRecord>>,
  'getMedicine' : ActorMethod<[string], [] | [Medicine]>,
  'getProfitLossStats' : ActorMethod<[ProfitLossTimeFilter], ProfitLossStats>,
  'getTotalBilledQuantity' : ActorMethod<[string], bigint>,
  'recordPayment' : ActorMethod<[bigint, bigint, string], undefined>,
  'reduceMedicineStock' : ActorMethod<[string, bigint], undefined>,
  'removeDoctorMedicinePrice' : ActorMethod<[string, string], undefined>,
  'setAppPin' : ActorMethod<[string], undefined>,
  'setDoctorMedicinePrice' : ActorMethod<[string, string, bigint], undefined>,
  'updateDoctor' : ActorMethod<[string, string], undefined>,
  'updateFirmSettings' : ActorMethod<
    [string, string, string, string, string, string, string],
    undefined
  >,
  'updateOpeningStock' : ActorMethod<[string, bigint], undefined>,
  'updateSampling' : ActorMethod<[string, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];