/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const InvoiceItem = IDL.Record({
  'purchaseRate' : IDL.Int,
  'expiryDate' : IDL.Text,
  'sellingPrice' : IDL.Int,
  'hsnCode' : IDL.Text,
  'batchNumber' : IDL.Text,
  'quantity' : IDL.Int,
  'profit' : IDL.Int,
  'amount' : IDL.Int,
  'medicineName' : IDL.Text,
});
export const Invoice = IDL.Record({
  'gstAmount' : IDL.Int,
  'amountPaid' : IDL.Int,
  'grandTotal' : IDL.Int,
  'totalProfit' : IDL.Int,
  'invoiceNumber' : IDL.Nat,
  'timestamp' : IDL.Int,
  'paymentType' : IDL.Text,
  'amountDue' : IDL.Int,
  'items' : IDL.Vec(InvoiceItem),
  'doctorName' : IDL.Text,
  'subtotal' : IDL.Int,
});
export const Medicine = IDL.Record({
  'mrp' : IDL.Int,
  'purchaseRate' : IDL.Int,
  'expiryDate' : IDL.Text,
  'name' : IDL.Text,
  'hsnCode' : IDL.Text,
  'baseSellingRate' : IDL.Int,
  'batchNumber' : IDL.Text,
  'quantity' : IDL.Int,
  'sampling' : IDL.Int,
  'openingStock' : IDL.Int,
});
export const FirmSettings = IDL.Record({
  'contact' : IDL.Text,
  'dilNumber' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'gstin' : IDL.Text,
  'address' : IDL.Text,
  'defaultShippingAddress' : IDL.Text,
});
export const Doctor = IDL.Record({
  'name' : IDL.Text,
  'customPrices' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Int)),
  'shippingAddress' : IDL.Text,
});
export const PaymentRecord = IDL.Record({
  'invoiceNumber' : IDL.Nat,
  'timestamp' : IDL.Int,
  'paymentDate' : IDL.Text,
  'amount' : IDL.Int,
});
export const BackupRecord = IDL.Record({
  'version' : IDL.Text,
  'timestamp' : IDL.Int,
  'invoices' : IDL.Vec(Invoice),
  'medicines' : IDL.Vec(Medicine),
  'firmSettings' : IDL.Opt(FirmSettings),
  'doctors' : IDL.Vec(Doctor),
  'paymentRecords' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Vec(PaymentRecord))),
});
export const LedgerSummary = IDL.Record({
  'totalCredit' : IDL.Int,
  'totalPaid' : IDL.Nat,
  'outstandingBalance' : IDL.Nat,
  'doctorName' : IDL.Text,
});
export const ProfitLossTimeFilter = IDL.Variant({
  'all' : IDL.Null,
  'monthly' : IDL.Null,
  'daily' : IDL.Null,
  'weekly' : IDL.Null,
});
export const ProfitLossStats = IDL.Record({
  'invoiceCount' : IDL.Nat,
  'totalCost' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
  'profitMargin' : IDL.Int,
  'netProfit' : IDL.Int,
});

export const idlService = IDL.Service({
  'addDoctor' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addOrUpdateMedicine' : IDL.Func(
      [
        IDL.Text,
        IDL.Int,
        IDL.Int,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Int,
        IDL.Int,
      ],
      [],
      [],
    ),
  'backup' : IDL.Func([], [BackupRecord], ['query']),
  'createInvoice' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Int)), IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteDoctor' : IDL.Func([IDL.Text], [], []),
  'deleteInvoice' : IDL.Func([IDL.Nat], [], []),
  'deleteMedicine' : IDL.Func([IDL.Text], [], []),
  'getAllDoctorPrices' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Int))],
      ['query'],
    ),
  'getAllDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
  'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getAllMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
  'getAppPin' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getDoctor' : IDL.Func([IDL.Text], [IDL.Opt(Doctor)], ['query']),
  'getDoctorLedgerSummary' : IDL.Func([IDL.Text], [LedgerSummary], ['query']),
  'getDoctorMedicinePrice' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Int],
      ['query'],
    ),
  'getFirmSettings' : IDL.Func([], [FirmSettings], ['query']),
  'getInvoice' : IDL.Func([IDL.Nat], [IDL.Opt(Invoice)], ['query']),
  'getInvoicePayments' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(PaymentRecord)],
      ['query'],
    ),
  'getMedicine' : IDL.Func([IDL.Text], [IDL.Opt(Medicine)], ['query']),
  'getProfitLossStats' : IDL.Func(
      [ProfitLossTimeFilter],
      [ProfitLossStats],
      ['query'],
    ),
  'getTotalBilledQuantity' : IDL.Func([IDL.Text], [IDL.Int], ['query']),
  'recordPayment' : IDL.Func([IDL.Nat, IDL.Int, IDL.Text], [], []),
  'reduceMedicineStock' : IDL.Func([IDL.Text, IDL.Int], [], []),
  'removeDoctorMedicinePrice' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setAppPin' : IDL.Func([IDL.Text], [], []),
  'setDoctorMedicinePrice' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [], []),
  'updateDoctor' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateFirmSettings' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateOpeningStock' : IDL.Func([IDL.Text, IDL.Int], [], []),
  'updateSampling' : IDL.Func([IDL.Text, IDL.Int], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const InvoiceItem = IDL.Record({
    'purchaseRate' : IDL.Int,
    'expiryDate' : IDL.Text,
    'sellingPrice' : IDL.Int,
    'hsnCode' : IDL.Text,
    'batchNumber' : IDL.Text,
    'quantity' : IDL.Int,
    'profit' : IDL.Int,
    'amount' : IDL.Int,
    'medicineName' : IDL.Text,
  });
  const Invoice = IDL.Record({
    'gstAmount' : IDL.Int,
    'amountPaid' : IDL.Int,
    'grandTotal' : IDL.Int,
    'totalProfit' : IDL.Int,
    'invoiceNumber' : IDL.Nat,
    'timestamp' : IDL.Int,
    'paymentType' : IDL.Text,
    'amountDue' : IDL.Int,
    'items' : IDL.Vec(InvoiceItem),
    'doctorName' : IDL.Text,
    'subtotal' : IDL.Int,
  });
  const Medicine = IDL.Record({
    'mrp' : IDL.Int,
    'purchaseRate' : IDL.Int,
    'expiryDate' : IDL.Text,
    'name' : IDL.Text,
    'hsnCode' : IDL.Text,
    'baseSellingRate' : IDL.Int,
    'batchNumber' : IDL.Text,
    'quantity' : IDL.Int,
    'sampling' : IDL.Int,
    'openingStock' : IDL.Int,
  });
  const FirmSettings = IDL.Record({
    'contact' : IDL.Text,
    'dilNumber' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'gstin' : IDL.Text,
    'address' : IDL.Text,
    'defaultShippingAddress' : IDL.Text,
  });
  const Doctor = IDL.Record({
    'name' : IDL.Text,
    'customPrices' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Int)),
    'shippingAddress' : IDL.Text,
  });
  const PaymentRecord = IDL.Record({
    'invoiceNumber' : IDL.Nat,
    'timestamp' : IDL.Int,
    'paymentDate' : IDL.Text,
    'amount' : IDL.Int,
  });
  const BackupRecord = IDL.Record({
    'version' : IDL.Text,
    'timestamp' : IDL.Int,
    'invoices' : IDL.Vec(Invoice),
    'medicines' : IDL.Vec(Medicine),
    'firmSettings' : IDL.Opt(FirmSettings),
    'doctors' : IDL.Vec(Doctor),
    'paymentRecords' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Vec(PaymentRecord))),
  });
  const LedgerSummary = IDL.Record({
    'totalCredit' : IDL.Int,
    'totalPaid' : IDL.Nat,
    'outstandingBalance' : IDL.Nat,
    'doctorName' : IDL.Text,
  });
  const ProfitLossTimeFilter = IDL.Variant({
    'all' : IDL.Null,
    'monthly' : IDL.Null,
    'daily' : IDL.Null,
    'weekly' : IDL.Null,
  });
  const ProfitLossStats = IDL.Record({
    'invoiceCount' : IDL.Nat,
    'totalCost' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
    'profitMargin' : IDL.Int,
    'netProfit' : IDL.Int,
  });
  
  return IDL.Service({
    'addDoctor' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addOrUpdateMedicine' : IDL.Func(
        [
          IDL.Text,
          IDL.Int,
          IDL.Int,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Int,
          IDL.Int,
        ],
        [],
        [],
      ),
    'backup' : IDL.Func([], [BackupRecord], ['query']),
    'createInvoice' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Int)), IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteDoctor' : IDL.Func([IDL.Text], [], []),
    'deleteInvoice' : IDL.Func([IDL.Nat], [], []),
    'deleteMedicine' : IDL.Func([IDL.Text], [], []),
    'getAllDoctorPrices' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Int))],
        ['query'],
      ),
    'getAllDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
    'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getAllMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
    'getAppPin' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getDoctor' : IDL.Func([IDL.Text], [IDL.Opt(Doctor)], ['query']),
    'getDoctorLedgerSummary' : IDL.Func([IDL.Text], [LedgerSummary], ['query']),
    'getDoctorMedicinePrice' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Int],
        ['query'],
      ),
    'getFirmSettings' : IDL.Func([], [FirmSettings], ['query']),
    'getInvoice' : IDL.Func([IDL.Nat], [IDL.Opt(Invoice)], ['query']),
    'getInvoicePayments' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(PaymentRecord)],
        ['query'],
      ),
    'getMedicine' : IDL.Func([IDL.Text], [IDL.Opt(Medicine)], ['query']),
    'getProfitLossStats' : IDL.Func(
        [ProfitLossTimeFilter],
        [ProfitLossStats],
        ['query'],
      ),
    'getTotalBilledQuantity' : IDL.Func([IDL.Text], [IDL.Int], ['query']),
    'recordPayment' : IDL.Func([IDL.Nat, IDL.Int, IDL.Text], [], []),
    'reduceMedicineStock' : IDL.Func([IDL.Text, IDL.Int], [], []),
    'removeDoctorMedicinePrice' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setAppPin' : IDL.Func([IDL.Text], [], []),
    'setDoctorMedicinePrice' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [], []),
    'updateDoctor' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateFirmSettings' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateOpeningStock' : IDL.Func([IDL.Text, IDL.Int], [], []),
    'updateSampling' : IDL.Func([IDL.Text, IDL.Int], [], []),
  });
};

export const init = ({ IDL }) => { return []; };