/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Doctor { 'marginPercentage' : bigint, 'name' : string }
export interface FirmSettings {
  'contact' : string,
  'name' : string,
  'email' : string,
  'gstin' : string,
  'address' : string,
  'shippingAddress' : string,
}
export interface Invoice {
  'totalCgst' : bigint,
  'totalSgst' : bigint,
  'grandTotal' : bigint,
  'invoiceNumber' : bigint,
  'totalAmount' : bigint,
  'items' : Array<InvoiceItem>,
  'doctorName' : string,
}
export interface InvoiceItem {
  'marginPercentage' : bigint,
  'expiryDate' : string,
  'cgst' : bigint,
  'rate' : bigint,
  'sgst' : bigint,
  'hsnCode' : string,
  'totalAmount' : bigint,
  'batchNumber' : string,
  'quantity' : bigint,
  'amount' : bigint,
  'medicineName' : string,
}
export interface Medicine {
  'mrp' : bigint,
  'purchaseRate' : bigint,
  'expiryDate' : string,
  'name' : string,
  'hsnCode' : string,
  'sellingRate' : bigint,
  'batchNumber' : string,
  'quantity' : bigint,
}
export interface _SERVICE {
  'addOrUpdateDoctor' : ActorMethod<[string, bigint], undefined>,
  'addOrUpdateMedicine' : ActorMethod<
    [string, bigint, string, string, string, bigint, bigint, bigint],
    undefined
  >,
  'createInvoice' : ActorMethod<[string, Array<[string, bigint]>], bigint>,
  'deleteDoctor' : ActorMethod<[string], undefined>,
  'deleteInvoice' : ActorMethod<[bigint], undefined>,
  'deleteMedicine' : ActorMethod<[string], undefined>,
  'getAllDoctors' : ActorMethod<[], Array<Doctor>>,
  'getAllInvoices' : ActorMethod<[], Array<Invoice>>,
  'getAllMedicines' : ActorMethod<[], Array<Medicine>>,
  'getDoctor' : ActorMethod<[string], Doctor>,
  'getFirmSettings' : ActorMethod<[], FirmSettings>,
  'getInvoice' : ActorMethod<[bigint], [] | [Invoice]>,
  'getMedicine' : ActorMethod<[string], [] | [Medicine]>,
  'reduceMedicineStock' : ActorMethod<[string, bigint], undefined>,
  'updateFirmSettings' : ActorMethod<
    [string, string, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];