/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Doctor = IDL.Record({
  'marginPercentage' : IDL.Int,
  'name' : IDL.Text,
});
export const InvoiceItem = IDL.Record({
  'marginPercentage' : IDL.Int,
  'cgst' : IDL.Int,
  'rate' : IDL.Int,
  'sgst' : IDL.Int,
  'hsnCode' : IDL.Text,
  'totalAmount' : IDL.Int,
  'batchNumber' : IDL.Text,
  'quantity' : IDL.Nat,
  'amount' : IDL.Int,
  'medicineName' : IDL.Text,
});
export const Invoice = IDL.Record({
  'totalCgst' : IDL.Int,
  'totalSgst' : IDL.Int,
  'grandTotal' : IDL.Int,
  'invoiceNumber' : IDL.Nat,
  'totalAmount' : IDL.Int,
  'items' : IDL.Vec(InvoiceItem),
  'doctorName' : IDL.Text,
});
export const Medicine = IDL.Record({
  'mrp' : IDL.Int,
  'purchaseRate' : IDL.Int,
  'expiryDate' : IDL.Text,
  'name' : IDL.Text,
  'hsnCode' : IDL.Text,
  'sellingRate' : IDL.Int,
  'batchNumber' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const FirmSettings = IDL.Record({
  'contact' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'gstin' : IDL.Text,
  'address' : IDL.Text,
  'shippingAddress' : IDL.Text,
});

export const idlService = IDL.Service({
  'addOrUpdateDoctor' : IDL.Func([IDL.Text, IDL.Int], [], []),
  'addOrUpdateMedicine' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Int,
        IDL.Int,
      ],
      [],
      [],
    ),
  'createInvoice' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      [IDL.Nat],
      [],
    ),
  'deleteDoctor' : IDL.Func([IDL.Text], [], []),
  'deleteMedicine' : IDL.Func([IDL.Text], [], []),
  'getAllDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
  'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getAllMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
  'getDoctor' : IDL.Func([IDL.Text], [Doctor], ['query']),
  'getFirmSettings' : IDL.Func([], [FirmSettings], ['query']),
  'getInvoice' : IDL.Func([IDL.Nat], [Invoice], ['query']),
  'getMedicine' : IDL.Func([IDL.Text], [Medicine], ['query']),
  'updateFirmSettings' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Doctor = IDL.Record({
    'marginPercentage' : IDL.Int,
    'name' : IDL.Text,
  });
  const InvoiceItem = IDL.Record({
    'marginPercentage' : IDL.Int,
    'cgst' : IDL.Int,
    'rate' : IDL.Int,
    'sgst' : IDL.Int,
    'hsnCode' : IDL.Text,
    'totalAmount' : IDL.Int,
    'batchNumber' : IDL.Text,
    'quantity' : IDL.Nat,
    'amount' : IDL.Int,
    'medicineName' : IDL.Text,
  });
  const Invoice = IDL.Record({
    'totalCgst' : IDL.Int,
    'totalSgst' : IDL.Int,
    'grandTotal' : IDL.Int,
    'invoiceNumber' : IDL.Nat,
    'totalAmount' : IDL.Int,
    'items' : IDL.Vec(InvoiceItem),
    'doctorName' : IDL.Text,
  });
  const Medicine = IDL.Record({
    'mrp' : IDL.Int,
    'purchaseRate' : IDL.Int,
    'expiryDate' : IDL.Text,
    'name' : IDL.Text,
    'hsnCode' : IDL.Text,
    'sellingRate' : IDL.Int,
    'batchNumber' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  const FirmSettings = IDL.Record({
    'contact' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'gstin' : IDL.Text,
    'address' : IDL.Text,
    'shippingAddress' : IDL.Text,
  });
  
  return IDL.Service({
    'addOrUpdateDoctor' : IDL.Func([IDL.Text, IDL.Int], [], []),
    'addOrUpdateMedicine' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Int,
          IDL.Int,
        ],
        [],
        [],
      ),
    'createInvoice' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        [IDL.Nat],
        [],
      ),
    'deleteDoctor' : IDL.Func([IDL.Text], [], []),
    'deleteMedicine' : IDL.Func([IDL.Text], [], []),
    'getAllDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
    'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getAllMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
    'getDoctor' : IDL.Func([IDL.Text], [Doctor], ['query']),
    'getFirmSettings' : IDL.Func([], [FirmSettings], ['query']),
    'getInvoice' : IDL.Func([IDL.Nat], [Invoice], ['query']),
    'getMedicine' : IDL.Func([IDL.Text], [Medicine], ['query']),
    'updateFirmSettings' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };