/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BackupRecord {
    version: string;
    timestamp: bigint;
    invoices: Array<Invoice>;
    medicines: Array<Medicine>;
    firmSettings?: FirmSettings;
    doctors: Array<Doctor>;
    paymentRecords: Array<[bigint, Array<PaymentRecord>]>;
}
export interface InvoiceItem {
    purchaseRate: bigint;
    expiryDate: string;
    sellingPrice: bigint;
    hsnCode: string;
    batchNumber: string;
    quantity: bigint;
    profit: bigint;
    amount: bigint;
    medicineName: string;
}
export interface FirmSettings {
    contact: string;
    dilNumber: string;
    name: string;
    email: string;
    gstin: string;
    address: string;
    defaultShippingAddress: string;
}
export interface PaymentRecord {
    invoiceNumber: bigint;
    timestamp: bigint;
    paymentDate: string;
    amount: bigint;
}
export interface ProfitLossStats {
    invoiceCount: bigint;
    totalCost: bigint;
    totalRevenue: bigint;
    profitMargin: bigint;
    netProfit: bigint;
}
export interface Medicine {
    mrp: bigint;
    purchaseRate: bigint;
    expiryDate: string;
    name: string;
    hsnCode: string;
    baseSellingRate: bigint;
    batchNumber: string;
    quantity: bigint;
    sampling: bigint;
    openingStock: bigint;
}
export interface Invoice {
    gstAmount: bigint;
    amountPaid: bigint;
    grandTotal: bigint;
    totalProfit: bigint;
    invoiceNumber: bigint;
    timestamp: bigint;
    paymentType: string;
    amountDue: bigint;
    items: Array<InvoiceItem>;
    doctorName: string;
    subtotal: bigint;
}
export interface Doctor {
    name: string;
    customPrices: Array<[string, bigint]>;
    shippingAddress: string;
}
export interface LedgerSummary {
    totalCredit: bigint;
    totalPaid: bigint;
    outstandingBalance: bigint;
    doctorName: string;
}
export enum ProfitLossTimeFilter {
    all = "all",
    monthly = "monthly",
    daily = "daily",
    weekly = "weekly"
}
export interface backendInterface {
    addDoctor(name: string, shippingAddress: string): Promise<void>;
    addOrUpdateMedicine(name: string, openingStock: bigint, sampling: bigint, batchNumber: string, hsnCode: string, expiryDate: string, purchaseRate: bigint, baseSellingRate: bigint, mrp: bigint): Promise<void>;
    backup(): Promise<BackupRecord>;
    createInvoice(doctorName: string, items: Array<[string, bigint]>, paymentType: string): Promise<bigint>;
    deleteDoctor(name: string): Promise<void>;
    deleteInvoice(invoiceNumber: bigint): Promise<void>;
    deleteMedicine(name: string): Promise<void>;
    getAllDoctorPrices(doctorName: string): Promise<Array<[string, bigint]>>;
    getAllDoctors(): Promise<Array<Doctor>>;
    getAllInvoices(): Promise<Array<Invoice>>;
    getAllMedicines(): Promise<Array<Medicine>>;
    getAppPin(): Promise<string | null>;
    getDoctor(name: string): Promise<Doctor | null>;
    getDoctorLedgerSummary(doctorName: string): Promise<LedgerSummary>;
    getDoctorMedicinePrice(doctorName: string, medicineName: string): Promise<bigint>;
    getFirmSettings(): Promise<FirmSettings>;
    getInvoice(invoiceNumber: bigint): Promise<Invoice | null>;
    getInvoicePayments(invoiceNumber: bigint): Promise<Array<PaymentRecord>>;
    getMedicine(name: string): Promise<Medicine | null>;
    getProfitLossStats(filter: ProfitLossTimeFilter): Promise<ProfitLossStats>;
    getTotalBilledQuantity(name: string): Promise<bigint>;
    recordPayment(invoiceNumber: bigint, amount: bigint, paymentDate: string): Promise<void>;
    reduceMedicineStock(name: string, quantity: bigint): Promise<void>;
    removeDoctorMedicinePrice(doctorName: string, medicineName: string): Promise<void>;
    setAppPin(pin: string): Promise<void>;
    setDoctorMedicinePrice(doctorName: string, medicineName: string, price: bigint): Promise<void>;
    updateDoctor(name: string, shippingAddress: string): Promise<void>;
    updateFirmSettings(name: string, address: string, gstin: string, contact: string, email: string, defaultShippingAddress: string, dilNumber: string): Promise<void>;
    updateOpeningStock(name: string, openingStock: bigint): Promise<void>;
    updateSampling(name: string, sampling: bigint): Promise<void>;
}
import type { BackupRecord as _BackupRecord, Doctor as _Doctor, FirmSettings as _FirmSettings, Invoice as _Invoice, Medicine as _Medicine, PaymentRecord as _PaymentRecord, ProfitLossTimeFilter as _ProfitLossTimeFilter } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addDoctor(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDoctor(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDoctor(arg0, arg1);
            return result;
        }
    }
    async addOrUpdateMedicine(arg0: string, arg1: bigint, arg2: bigint, arg3: string, arg4: string, arg5: string, arg6: bigint, arg7: bigint, arg8: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateMedicine(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateMedicine(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async backup(): Promise<BackupRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.backup();
                return from_candid_BackupRecord_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.backup();
            return from_candid_BackupRecord_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createInvoice(arg0: string, arg1: Array<[string, bigint]>, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createInvoice(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInvoice(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteDoctor(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDoctor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDoctor(arg0);
            return result;
        }
    }
    async deleteInvoice(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInvoice(arg0);
            return result;
        }
    }
    async deleteMedicine(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMedicine(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMedicine(arg0);
            return result;
        }
    }
    async getAllDoctorPrices(arg0: string): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDoctorPrices(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDoctorPrices(arg0);
            return result;
        }
    }
    async getAllDoctors(): Promise<Array<Doctor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDoctors();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDoctors();
            return result;
        }
    }
    async getAllInvoices(): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInvoices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInvoices();
            return result;
        }
    }
    async getAllMedicines(): Promise<Array<Medicine>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMedicines();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMedicines();
            return result;
        }
    }
    async getAppPin(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppPin();
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppPin();
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDoctor(arg0: string): Promise<Doctor | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoctor(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoctor(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDoctorLedgerSummary(arg0: string): Promise<LedgerSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoctorLedgerSummary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoctorLedgerSummary(arg0);
            return result;
        }
    }
    async getDoctorMedicinePrice(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoctorMedicinePrice(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoctorMedicinePrice(arg0, arg1);
            return result;
        }
    }
    async getFirmSettings(): Promise<FirmSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getFirmSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFirmSettings();
            return result;
        }
    }
    async getInvoice(arg0: bigint): Promise<Invoice | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoice(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoice(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvoicePayments(arg0: bigint): Promise<Array<PaymentRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoicePayments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoicePayments(arg0);
            return result;
        }
    }
    async getMedicine(arg0: string): Promise<Medicine | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMedicine(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMedicine(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfitLossStats(arg0: ProfitLossTimeFilter): Promise<ProfitLossStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfitLossStats(to_candid_ProfitLossTimeFilter_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfitLossStats(to_candid_ProfitLossTimeFilter_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getTotalBilledQuantity(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalBilledQuantity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalBilledQuantity(arg0);
            return result;
        }
    }
    async recordPayment(arg0: bigint, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordPayment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordPayment(arg0, arg1, arg2);
            return result;
        }
    }
    async reduceMedicineStock(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reduceMedicineStock(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reduceMedicineStock(arg0, arg1);
            return result;
        }
    }
    async removeDoctorMedicinePrice(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeDoctorMedicinePrice(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeDoctorMedicinePrice(arg0, arg1);
            return result;
        }
    }
    async setAppPin(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAppPin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAppPin(arg0);
            return result;
        }
    }
    async setDoctorMedicinePrice(arg0: string, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setDoctorMedicinePrice(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDoctorMedicinePrice(arg0, arg1, arg2);
            return result;
        }
    }
    async updateDoctor(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDoctor(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDoctor(arg0, arg1);
            return result;
        }
    }
    async updateFirmSettings(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFirmSettings(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFirmSettings(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateOpeningStock(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOpeningStock(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOpeningStock(arg0, arg1);
            return result;
        }
    }
    async updateSampling(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSampling(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSampling(arg0, arg1);
            return result;
        }
    }
}
function from_candid_BackupRecord_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BackupRecord): BackupRecord {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FirmSettings]): FirmSettings | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Doctor]): Doctor | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Invoice]): Invoice | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Medicine]): Medicine | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    version: string;
    timestamp: bigint;
    invoices: Array<_Invoice>;
    medicines: Array<_Medicine>;
    firmSettings: [] | [_FirmSettings];
    doctors: Array<_Doctor>;
    paymentRecords: Array<[bigint, Array<_PaymentRecord>]>;
}): {
    version: string;
    timestamp: bigint;
    invoices: Array<Invoice>;
    medicines: Array<Medicine>;
    firmSettings?: FirmSettings;
    doctors: Array<Doctor>;
    paymentRecords: Array<[bigint, Array<PaymentRecord>]>;
} {
    return {
        version: value.version,
        timestamp: value.timestamp,
        invoices: value.invoices,
        medicines: value.medicines,
        firmSettings: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.firmSettings)),
        doctors: value.doctors,
        paymentRecords: value.paymentRecords
    };
}
function to_candid_ProfitLossTimeFilter_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProfitLossTimeFilter): _ProfitLossTimeFilter {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProfitLossTimeFilter): {
    all: null;
} | {
    monthly: null;
} | {
    daily: null;
} | {
    weekly: null;
} {
    return value == ProfitLossTimeFilter.all ? {
        all: null
    } : value == ProfitLossTimeFilter.monthly ? {
        monthly: null
    } : value == ProfitLossTimeFilter.daily ? {
        daily: null
    } : value == ProfitLossTimeFilter.weekly ? {
        weekly: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
